### ISSUE TITLE
Make install does not work

### ISSUE THREAD

**Issue by jose1711** [iustin/bakonf#1]
I wonder if `Makefile` is broken and requires an update.
```
$ git clone https://github.com/iustin/bakonf.git
$ cd bakonf
$ make DESTDIR=/tmp/test install
install -d -m 0700 /tmp/test/etc/bakonf
install -d -m 0700 /tmp/test/etc/bakonf/sources
install -d -m 0700 /tmp/test/var/lib/bakonf
install -d -m 0700 /tmp/test/var/lib/bakonf/archives
install -D -m 0700 bakonf /tmp/test/usr/bin/bakonf
install: cannot stat 'bakonf': No such file or directory
make: *** [Makefile:28: install] Error 1
```

**Comment by iustin** [comment]
Ah, I don't think I've used `make install` in ages. Thanks for the report!

**Comment by jose1711** [comment]
Thank you for the fix - `make install` is being used in [`PKGBUILD`](https://aur.archlinux.org/packages/bakonf/) for Arch Linux which is due to be updated.

**Comment by iustin** [comment]
Oh, I didn't this is in Arch. I mean, I'm a Debian developer, but I didn't upload it to Debian as I didn't think other people would use it besides myself :)

I've seen the other issue you filled, I guess there might be others that prevent clean packaging. Sorry :)
